# .github/workflows/deploy.yml
name: Build and Deploy to Server

on:
  workflow_dispatch:

env:
  IMAGE_NAME: charmflex/tlv-decoder:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker image
      run: docker push $IMAGE_NAME

    - name: Copy docker-compose.yml to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SSH_PW }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "docker-compose.yml"
        target: "/servers/tlv-decoder/"

    - name: pull image and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SSH_KEY }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd servers/tlv-decoder
          docker compose up -d
